import type { Metadata } from "next";
import { MuseoModerno, Noto_Sans_KR, Work_Sans } from "next/font/google";
import AppShell from "@/components/layout/AppShell";
import "./globals.css";

const workSans = Work_Sans({
  variable: "--app-font-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const museoModerno = MuseoModerno({
  variable: "--app-font-display",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

const notoSansKr = Noto_Sans_KR({
  variable: "--app-font-kr",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Welcome to PNUops",
  description: "Generated by PNUops",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.variable} ${museoModerno.variable} ${notoSansKr.variable} antialiased`}
      >
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}
